#!/bin/bash 
 
if [[ -n "$DISABLE_MAILHOG" ]]; then
	echo "MailHog is disabled, not starting services."
elif [[ "$APP_NAME" = "dev" ]]; then
    exec /data/var/home/gonano/go/bin/MailHog -ui-web-path mailbox -maildir-path /app/storage/mailhog -storage maildir 
else
    PWD=$(/data/var/home/gonano/go/bin/MailHog bcrypt $MAIL_PASS) 
    echo "$MAIL_USER:$PWD" > /tmp/mailhog.auth 
    exec /data/var/home/gonano/go/bin/MailHog -ui-web-path mailbox -maildir-path /app/storage/mailhog -storage maildir -auth-file /tmp/mailhog.auth 
fi 